name: phpunit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.1', '8.0', '7.4']
        twill: ['3.0.0-rc4', '2.*']
        include:
          - php: '8.2'
            dusk: '7.*'
            testbench: '7.*'
          - php: '8.1'
            dusk: '7.*'
            testbench: '7.*'
          - php: '8.0'
            dusk: '7.*'
            testbench: '7.*'
          - php: '7.4'
            dusk: '6.*'
            testbench: '6.*'
        exclude:
          - twill: '3.0.0-rc4'
            php: '7.4'

    name: P${{ matrix.php }} T${{ matrix.twill }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: ${{ matrix.php }}

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-P${{ matrix.php }}-T${{ matrix.twill }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-P${{ matrix.php }}-P${{ matrix.twill }}-composer-

    - name: Prepare stubs
      run: |
        cd tests
        bash prepare_stubs.sh "${{ matrix.twill }}"

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: |
        composer require "orchestra/testbench:${{ matrix.testbench }}" "laravel/dusk:${{ matrix.dusk }}" "area17/twill:${{ matrix.twill }}" --no-interaction --no-update
        composer install --prefer-dist --no-interaction --no-plugins

    - name: Run test suite
      run: php vendor/bin/phpunit
